### ISSUE TITLE
[Enhancement] Support for Xiaomi Mijia 1080P Home Panoramic WiFi IP Camera

### ISSUE THREAD

**Issue by DJay-X** [josepramon/homebridge-mijia-camera#1]
@josepramon thanks for your work and sharing.
Any Idea if your plugin will work with the Xiaomi Mijia 1080P Home Panoramic WiFi IP Camera?
https://www.gearbest.com/ip-cameras/pp_009991451325.html?wid=1433363
And any plans for ongoing development? At the moment the plugin works as an on/off switch when I get this right?

Thanks again for the time you are investing.
DJay

![20180718115734_62475](https://user-images.githubusercontent.com/3874239/44984022-93c80e80-af7b-11e8-8cc6-77d8b7d631b8.jpg)

**Comment by josepramon** [comment]
Hi, to be honest I don't know if the plugin will work with that specific camera.
In my experience, different Xiaomi cameras have different APIs (that's the reason I created this plugin based on this other one: https://github.com/seikan/homebridge-mi-camera).

So, you will need to try.
Although I don't have any immediate plans to add support for other cameras, but it should be pretty easy, if you can figure out what commands expects the camera.

So, for example, for the the Xiaomi Mijia 1080P Smart IP Camera, in order to get the current state, one needs to read a property `power` from the camera, and to change the value, the command is `set_power ` with the appropriate value.
With another Xiaomi camera, the property and the command maybe are named differently.

**Comment by DJay-X** [comment]
Just want to let you know, that the above cam also works On/Sleep with your plugin. 👍🏻
Thx.
