### ISSUE TITLE
two way audio

### ISSUE THREAD

**Issue by Partizan7676** [josepramon/homebridge-mijia-camera#4]
Everybody makes tons of same plugin - just changing name and initial parameters. but you do it for camera with mic and speaker - do they work?

**Comment by josepramon** [comment]
As far as I know, there is no public API for the camera, or any documentation available, so implementing new features to the plugin is not easy.
So far, the only feature implemented is toggling on and off the camera, because that one was not that Figuring out what other commands accepts the camera would make possible to implement new features.

[Here](https://github.com/sahilchaddha/homebridge-dafang#readme) there is another homebridge plugin for Xiaomi cameras that apparently supports audio/video, but it looks like it requires installing something on the camera itself.
